// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_54EHB-P5p9O7j1q9FwPwg1z-PeUkv0',
    appId: '1:3609488336:web:6e75e2803d4dfcc58f67d5',
    messagingSenderId: '3609488336',
    projectId: 'workshopmmamc',
    authDomain: 'workshopmmamc.firebaseapp.com',
    storageBucket: 'workshopmmamc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVMZKE1IHFU9ClyG6vZLiLY5-BIq6aGM',
    appId: '1:3609488336:android:f5098c7593633dc88f67d5',
    messagingSenderId: '3609488336',
    projectId: 'workshopmmamc',
    storageBucket: 'workshopmmamc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHHEdxEVYGVaSeO120cIF4B6fGTnFqeVA',
    appId: '1:3609488336:ios:7963543e4c882e318f67d5',
    messagingSenderId: '3609488336',
    projectId: 'workshopmmamc',
    storageBucket: 'workshopmmamc.appspot.com',
    iosClientId:
        '3609488336-36k2aq990gda1l3eej1vuegkq545a8p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshopproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHHEdxEVYGVaSeO120cIF4B6fGTnFqeVA',
    appId: '1:3609488336:ios:7963543e4c882e318f67d5',
    messagingSenderId: '3609488336',
    projectId: 'workshopmmamc',
    storageBucket: 'workshopmmamc.appspot.com',
    iosClientId:
        '3609488336-36k2aq990gda1l3eej1vuegkq545a8p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.workshopproject',
  );
}
